name: Build and Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch_build]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest # Specify preferred runner environment

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: 'true'

      - uses: actions/setup-node@v4
        with:
            node-version: lts/fermium

      - name: Install & Build
        working-directory: site
        run: |
            npm install
            gulp dist --codelabs-dir=./data/codelabs
    
