name: Dispatch Build and Push for PR

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch_build]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest # Specify preferred runner environment

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: 'true'

      - name: Commit changes in submodule site/data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git submodule update --remote site/data
          git rm --cached site/data
          git add site/data/*
          git commit -m "Update submodule site/data" || echo "No changes in submodule to commit"

      - name: Build Site
        uses: ./.github/workflows/build_site.yml@main

      - name: Check for worktree changes
        id: git-build-changes
        run: |
          rm -rf ./codelabs
          cp -rfL site/dist/* .
          if [ $(git status --porcelain | wc -l) -eq "0" ]; then   
            echo "is-changed=false" >> "$GITHUB_OUTPUT"
          else   
            echo "is-changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit changes
        if: steps.git-build-changes.outputs.is-changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "build(site): Codelabs has been updated" || echo "No changes to commit"
          git push -qf origin HEAD:github-actions-auto-build || echo "No changes to commit"

      - name: Create PR from Updated Branch
        if: steps.git-build-changes.outputs.is-changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo
            const branch = 'github-actions-auto-build'
            const head = `${owner}:${branch}`
            const title = 'build(site): Update site with new codelab(s) updates'
            const branchesResult = await github.rest.repos.listBranches({ owner, repo })
            if (branchesResult.status !== 200 || !branchesResult.data.find(({ name }) => name === branch)) {
              return
            }
            const prsResult = await github.rest.pulls.list({ owner, repo, head, state: 'open' })
            if (prsResult.status === 200 && prsResult.data.length === 0) {
              try {
                await github.rest.pulls.create({ owner, repo, head, title, base: 'main' })
              } catch (error) {
                console.error(error)
              }
            }
